puts "Seeding coffees..."

puts "☕️ Seeding products..."
Product.create!(id: 1, name: "Tis the Season", isSeasonal: true, isBestseller: false, featured: true, inStock: true, roast: "Blend", isSingleOrigin: false, description: "Every holiday season, you go out of your way to get the biggest turkey, the tastiest cakes, and the fanciest coffees for your family...only for your family to take a massive dump on everything. That's why we created this coffee: Featuring a blend of our oldest, cheapest coffees in a basic-b bag, you can look like you're treating your guests without actually treating them. Let them trash-talk while they eat your food and criticize your home. 'Tis the season to look out for you. So, stop going out of your way for them! They don't deserve the good stuff. Because they're trash.", price: 6, tastingNotes: "Criticism, Disappointment, Regret.", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 2, name: "The Good Stuff", isSeasonal: true, isBestseller: false, featured: true, inStock: true, roast: "Medium", isSingleOrigin: false, description: "It's the holidays and we all know that means: family. Bitter, critical family giving you looks whenever you eat a dinner roll and asking why you're still single, childless, or gay. Or maybe you're alone, and you'll be sitting in a diner on Christmas Eve wondering what went wrong. Either way, this coffee is for you: a cozy blend of our most popular seasonal beans in our (probably vain) attempts to rienstill some winter cheer to these difficult months. It's been a long year and you're still here, doing the best you can. You deserve the good stuff, whether you believe it or not. So get yourself a little something! All orders come with a seasonal mug and a virtual hug: may next year bring more real ones.", price: 10, tastingNotes: "Brown Sugar, Spices, Hope.", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 3, name: "Memories", isSeasonal: false, isBestseller: false, featured: false, inStock: true, roast: "Light", isSingleOrigin: false, description: "Iced tea on the porch with grandma. Building legos with loved ones on sunday afternoons. Christmas morning when Christmas mornings were good. Everyone has a few good memories, even if they're few and far between. But at the risk of sounding corny, every new day is a new chance for good memories--if we believe it's still possible. Let this cup of coffee help make those good memories, whether its by sharing it with loved ones or enjoying it alone with a good book. Don't give up yet, fellow person!", price: 17, tastingNotes: "Delicate Florals, Stone Fruit, Spices", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 4, name: "Fig's Finest", isSeasonal: false, isBestseller: false, featured: true, inStock: true, roast: "Blend", isSingleOrigin: false, description: "Fig works here. Fig has anxiety issues. Fig stays up late into the night, looking for that perfect roast, blend, and grind. Who is Fig, if Fig can't find that perfect coffee? What is Fig's worth, without that perfect coffee? Can anyone love Fig if Fig can't make that perfect cup of coffee? So, Fig works very hard to make that perfect cup of coffee. Featuring: Fig's Finest, the finest coffee that anxiety can make. It turns out, that's pretty fine coffee.", price: 18, tastingNotes: "Candied Citrus, Chocolate, Self-Worth", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 5, name: "Dark Mirror", isSeasonal: false, isBestseller: false, featured: false, inStock: true, roast: "Dark", isSingleOrigin: false, description: "Finally, a coffee as black as your soul. A coffee as black as the blackest night, which you are enjoying with your black coffee. Gaze into your mug and see your reflection in the black. You look tired. You have such heavy bags under your eyes. You need more coffee. For every bag of Dark Mirror coffee we sell, we donate $1 to the Mayo Clinic and their clinical trials on insomnia.", price: 14, tastingNotes: "Cloves, Bittersweet Chocolate, Self-Loathing", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 6, name: "By a Thread", isSeasonal: false, isBestseller: false, featured: false, inStock: true, roast: "Medium", isSingleOrigin: false, description: "When the daily grind grinds you down. When you're at the edge, hanging by a thread. When you just need a moment--here is your moment. A gentle medium roast made from a blend of our coziest beans to remind you that it's okay to take that moment.Hang in there, fellow person.", price: 14, tastingNotes: "Spices, Toffee, Peace", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 7, name: "3AM", isSeasonal: false, isBestseller: false, featured: false, inStock: true, roast: "Dark", isSingleOrigin: true, description: "Up late again, huh? We get it. Work goes late. Scrolling through TikTok goes late. And now its 3Am and you need to be up in a few hours. You heard that some sleep is better than no sleep, but you know you'll sleep through your alarm again. Plus, there's stuff to do. You'll sleep tomorrow--or this weekend. Unless you go crazy and die from sleep deprivation--that's a thing, you know. For every bag of 3AM coffee we sell, we donate $1 to the Harvard University's Division of Sleep Medicine.", price: 15, tastingNotes: "Caramel, Baking Spices, Cocoa, Insomnia", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")


Product.create!(id: 8, name: "Here, There, & Everywhere", isSeasonal: false, isBestseller: false, featured: false, inStock: true, roast: "Light", isSingleOrigin: true, description: "Agoraphobia", price: 18, tastingNotes: "Adventure", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 9, name: "Blonde Distraction", isSeasonal: false, isBestseller: false, featured: false, inStock: false, roast: "Light", isSingleOrigin: false, description: "Sex-addition", price: 17, tastingNotes: "Toasted Almonds, Peaches, Temptation", image: "https://pkgmaker.com/wp-content/uploads/2022/03/Amazing-Coffee-Packaging-Designs-1.png")

Product.create!(id: 10, name: "Sunny Days Ahead", isSeasonal: false, isBestseller: false, featured: "true", inStock: true, roast: "Light", isSingleOrigin: "true", description: "SAD", price: 15, tastingNotes: "Berries, Sweet Lemon, Honey, Sunlight", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 11, name: "Bone Daddy", isSeasonal: false, isBestseller: false, featured: "", inStock: true, roast: "Dark", isSingleOrigin: "false", description: "Schizophrenia", price: , tastingNotes: "TBD", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 12, name: "Blonde Distraction", isSeasonal: false, isBestseller: false, featured: false, inStock: false, roast: "Light", isSingleOrigin: false, description: "ADD - A lightly roasted, summery coffee. It's downright distracting, with its long beans and golden hue. Most things are distracting: you probably haven't even finished reading this description because you got distracted. But you won't be distracted from this coffee. No: this coffee will be the distraction.", price: 17, tastingNotes: "Toasted Almonds, Peaches, Temptation", image: "https://pkgmaker.com/wp-content/uploads/2022/03/Amazing-Coffee-Packaging-Designs-1.png")

Product.create!(id: 13, name: "Paris", isSeasonal: false, isBestseller: false, featured: "false", inStock: true, roast: "Dark", isSingleOrigin: "true", description: "Eating Disorders", price: , tastingNotes: "TBD", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 14, name: "TBD", isSeasonal: false, isBestseller: false, featured: "", inStock: true, roast: "Dark", isSingleOrigin: "false", description: "Bipolar", price: , tastingNotes: "TBD", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")

Product.create!(id: 15, name: "TBD", isSeasonal: false, isBestseller: false, featured: "", inStock: true, roast: "Dark", isSingleOrigin: "false", description: "PTSD", price: , tastingNotes: "TBD", image: "https://zippypixels.com/wp-content/uploads/2018/03/Plain-packaging-pouch-mockup.jpg")